// RegisterEmployee.jsx — Admin form to register a new employee account.
// After registering, the new login details stay on screen (with copy buttons) until the admin is done —
// the default password is generated by the backend (<EmployeeID>@<year>) and shown here once.
import { useState, useEffect } from "react";
import { useToast } from "../context/ToastContext";
import axios from "../services/axios";
import { useNavigate } from "react-router-dom";
import { X, Loader2, CheckCircle2, Copy, Check, UserPlus } from "lucide-react";

// Axios gives no response when the server can't be reached at all
const serverDown = (err) => !err?.response;

const RegisterEmployee = ({ setActiveTab }) => {
  const toast    = useToast();
  const navigate = useNavigate();

  const [form, setForm]             = useState({ name: "", email: "" });
  const [nextId, setNextId]         = useState("");
  const [idLoading, setIdLoading]   = useState(true);
  const [idError, setIdError]       = useState(null);
  const [submitting, setSubmitting] = useState(false);
  const [created, setCreated]       = useState(null); // { name, email, employeeId, password } after success
  const [copied, setCopied]         = useState(null); // which field was just copied

  // Fetch next auto-generated employee ID (the cancel flag stops React dev mode's double-run from toasting twice)
  const loadNextId = (isCancelled = () => false) => {
    setIdLoading(true);
    setIdError(null);
    axios.get("/users/next-employee-id")
      .then(r => { if (!isCancelled()) setNextId(r.data.nextId); })
      .catch(err => {
        if (isCancelled()) return;
        const msg = serverDown(err)
          ? "Can't reach the server — make sure the backend is running."
          : "Could not load the next Employee ID.";
        setIdError(msg);
        toast.error(msg);
      })
      .finally(() => { if (!isCancelled()) setIdLoading(false); });
  };

  useEffect(() => {
    let cancelled = false;
    loadNextId(() => cancelled);
    return () => { cancelled = true; };
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  const handleChange = (e) => setForm({ ...form, [e.target.name]: e.target.value });

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!nextId) return toast.error("Employee ID not ready yet.");
    setSubmitting(true);
    try {
      const { data } = await axios.post("/auth/register", {
        employeeId: nextId,
        name:       form.name,
        email:      form.email,
        role:       "employee",
      });
      setCreated({ name: data.name, email: data.email, employeeId: data.employeeId, password: data.defaultPassword });
      toast.success(`${data.name} registered.`);
    } catch (err) {
      toast.error(serverDown(err)
        ? "Can't reach the server — make sure the backend is running."
        : "Registration failed: " + (err?.response?.data?.message || err.message));
    } finally {
      setSubmitting(false);
    }
  };

  const copy = async (key, text) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(key);
      setTimeout(() => setCopied(c => (c === key ? null : c)), 1800);
    } catch {
      toast.error("Couldn't copy — select the text and copy it manually.");
    }
  };

  const registerAnother = () => {
    setCreated(null);
    setForm({ name: "", email: "" });
    loadNextId();
  };

  const handleClose = () => {
    if (typeof setActiveTab === "function") setActiveTab("employees");
    else navigate("/hr");
  };

  /* ── Success: login details stay until the admin is done ── */
  if (created) {
    const rows = [
      ["Employee ID", created.employeeId],
      ["Email", created.email],
      ["Password", created.password],
    ];
    const allText = `InsightDesk login\nName: ${created.name}\nEmployee ID: ${created.employeeId}\nEmail: ${created.email}\nPassword: ${created.password}`;
    return (
      <div className="flex justify-center items-center min-h-screen bg-gray-50">
        <div className="w-full max-w-md overflow-hidden rounded-2xl border border-gray-100 bg-white shadow-xl">
          <div className="h-1 bg-gradient-to-r from-indigo-500 via-violet-500 to-blue-500" />
          <div className="p-7">
            <div className="flex items-center gap-3">
              <div className="flex h-11 w-11 flex-shrink-0 items-center justify-center rounded-2xl bg-emerald-50">
                <CheckCircle2 className="h-6 w-6 text-emerald-500" />
              </div>
              <div className="min-w-0">
                <h2 className="text-lg font-bold text-gray-900">Employee registered</h2>
                <p className="truncate text-sm text-gray-500">{created.name}</p>
              </div>
            </div>

            <p className="mt-5 mb-2 text-[10px] font-bold uppercase tracking-widest text-gray-400">Login details to share</p>
            <ul className="space-y-2">
              {rows.map(([label, value]) => (
                <li key={label} className="flex items-center gap-3 rounded-xl border border-gray-100 bg-gray-50 px-3.5 py-2.5">
                  <div className="min-w-0 flex-1">
                    <p className="text-[10px] font-bold uppercase tracking-widest text-gray-400">{label}</p>
                    <p className={`mt-0.5 select-all truncate text-sm font-semibold text-gray-800 ${label !== "Email" ? "font-mono tracking-wide" : ""}`}>{value}</p>
                  </div>
                  <button type="button" onClick={() => copy(label, value)}
                    className="flex flex-shrink-0 items-center gap-1 rounded-full border border-gray-200 bg-white px-2.5 py-1 text-[11px] font-semibold text-gray-500 transition hover:bg-gray-100"
                    aria-label={`Copy ${label}`}>
                    {copied === label ? <><Check className="h-3 w-3 text-emerald-500" /> Copied</> : <><Copy className="h-3 w-3" /> Copy</>}
                  </button>
                </li>
              ))}
            </ul>

            <button type="button" onClick={() => copy("all", allText)}
              className="mt-3 inline-flex w-full items-center justify-center gap-2 rounded-full border border-indigo-200 px-4 py-2 text-sm font-semibold text-indigo-600 transition hover:bg-indigo-50">
              {copied === "all" ? <><Check className="h-4 w-4" /> All details copied</> : <><Copy className="h-4 w-4" /> Copy all details</>}
            </button>

            <p className="mt-4 rounded-xl border border-amber-100 bg-amber-50 px-3.5 py-2.5 text-xs text-amber-700">
              This password is shown only now. Share it with the employee and ask them to change it after their first login.
            </p>

            <div className="mt-5 flex gap-3">
              <button type="button" onClick={registerAnother}
                className="inline-flex flex-1 items-center justify-center gap-1.5 rounded-full border border-gray-200 px-4 py-2 text-sm font-semibold text-gray-600 transition hover:bg-gray-50">
                <UserPlus className="h-4 w-4" /> Register another
              </button>
              <button type="button" onClick={handleClose}
                className="flex-1 rounded-full bg-gray-800 px-4 py-2 text-sm font-semibold text-white transition hover:bg-gray-900">
                Done
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="flex justify-center items-center min-h-screen bg-gray-50">
      <div className="bg-white p-8 rounded-2xl w-full max-w-md relative border border-gray-200">

        {/* Close button */}
        <button
          className="absolute top-4 left-4 text-gray-400 hover:text-gray-700"
          onClick={handleClose}
          aria-label="Close"
        >
          <X className="w-6 h-6" />
        </button>

        <h2 className="text-2xl font-bold text-center mb-2">Employee Registration</h2>
        <p className="text-center text-gray-500 text-sm mb-6">
          Register new employees. A default password will be generated automatically.
        </p>

        <form onSubmit={handleSubmit} className="space-y-4">

          {/* Employee ID — disabled, auto-generated */}
          <div>
            <div className="relative">
              <input
                type="text"
                value={idLoading ? "Generating…" : (nextId || "—")}
                disabled
                className="w-full px-4 py-2 border border-gray-200 rounded-md bg-gray-100
                           text-gray-500 font-mono tracking-widest cursor-not-allowed"
              />
              {idLoading && (
                <Loader2 className="absolute right-3 top-2.5 w-4 h-4 animate-spin text-gray-400" />
              )}
            </div>
            {idError && (
              <p className="mt-1.5 flex items-center justify-between gap-2 text-xs text-red-500">
                {idError}
                <button type="button" onClick={() => loadNextId()} className="font-semibold text-indigo-600 hover:underline">Retry</button>
              </p>
            )}
          </div>

          {/* Employee Name */}
          <input
            type="text"
            name="name"
            placeholder="Employee Name"
            value={form.name}
            onChange={handleChange}
            className="w-full px-4 py-2 border rounded-md focus:outline-none focus:ring"
            required
          />

          {/* Employee Email */}
          <input
            type="email"
            name="email"
            placeholder="Employee Email"
            value={form.email}
            onChange={handleChange}
            className="w-full px-4 py-2 border rounded-md focus:outline-none focus:ring"
            required
          />

          {/* Submit */}
          <button
            type="submit"
            disabled={submitting || idLoading || !nextId}
            className="w-full bg-gray-800 text-white py-2 rounded-md font-semibold
                       hover:bg-gray-900 transition flex items-center justify-center gap-2
                       disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {submitting && <Loader2 className="w-4 h-4 animate-spin" />}
            {submitting ? "Registering…" : "Register Employee"}
          </button>

        </form>
      </div>
    </div>
  );
};

export default RegisterEmployee;
